version: 0.2
phases:
  build:
    commands:
      - pip install -r requirements.txt -t .
      - aws cloudformation package --template-file template.yml --output-template-file template-out.yml --s3-bucket gokcedb-test-bucket-001